name: Build Project
on:
  push:
    branches: [ "main" ]

jobs:
  build-test-lint-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install C++ dependencies and Python for linting
      run: sudo apt-get update && sudo apt-get install -y g++ make python3-pip dpkg-dev

    - name: Install Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo usermod -aG docker $USER

    - name: Build project
      run: make

    - name: Run tests
      run: ./treeTester.out

    - name: Install cpplint
      run: pip3 install cpplint

    - name: Lint code
      run: cpplint *.cpp *.h

    - name: Build Docker image
      run: docker build -t bst-ci-cd .

    - name: Build .deb package
      run: make deb

    - name: Upload .deb artifact
      uses: actions/upload-artifact@v4
      with:
        name: tree-tester-deb
        path: tree-tester_1.0_amd64.deb